version: '3'
services:

  jenkins:
    image: jenkins/jenkins:latest
    container_name: Jenkins
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    volumes:
      - /home/adailsilva/Apps/Docker/Jenkins/jenkins_home:/var/jenkins_home
